name: 'Auto Assign'
on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: prem-modi-website/Github-Acition-test@v4.3.2
