on:
  push:
   branches:
      - master
name: Deploy website on push
jobs:
  Github-Acition-test:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get letest code
      uses: prem-modi-website/Github-Acition-test@v4.3.2
      
    - name: Sync files
      uses: prem-modi-website/Github-Acition-test@v4.3.2
      with:
        server: ftp.thebestbeta.com
        username: admin@thebestbeta.com
        password: DdxA{[)NaFd#
