on: push
name: Super-Linter
jobs:
  web-deploy:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Super-Linter
      uses: github/super-linter@v4.9.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
